# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  auto_ids: true

# Permalinks
permalink:        pretty

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-toc

exclude:
  - Gemfile
  - Gemfile.lock

baseurl: ""
url: ""

# Info
title: Microshare
description: Store, Protect & Share the data you want, the way you want.
email: docs@microshare.io
twitter: microshare_io
github: microshare
social_logo_path: /assets/brand/default-icon.png
social_image_path: /assets/brand/default-icon.png

# Custom vars
current_version:  0.1
docs_version:     0.1
repo:             https://github.com/microshare/microshare.github.io
blog:             https://microshare.io/blog
